name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Create and serve mock ldraw library
        run: |
          mkdir -p mock_assets
          python -c "import zipfile; zipfile.ZipFile('mock_assets/complete.zip', 'w').close()"
          python -m http.server 8000 --directory mock_assets &
          sleep 2

      - name: Run tests with pytest
        env:
          PYTHONPATH: .
          MANIFEST_PATH: manifest.json
          TMP_DIR: tmp

          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}

          REBRICKABLE_PARTS_CSV_URL: ${{ secrets.REBRICKABLE_PARTS_CSV_URL }}
          REBRICKABLE_CATEGORIES_CSV_URL: ${{ secrets.REBRICKABLE_CATEGORIES_CSV_URL }}
          REBRICKABLE_COLORS_CSV_URL: ${{ secrets.REBRICKABLE_COLORS_CSV_URL }}

          LDRAW_COMPLETE_LIBRARY_URL: "http://localhost:8000/complete.zip"
          LDRAW_COMPLETE_LIBRARY_WEBPAGE: ${{ secrets.LDRAW_COMPLETE_LIBRARY_WEBPAGE }}

          LOG_FILE: ${{ secrets.LOG_FILE }}
          CLOUDWATCH_LOG_GROUP: ${{ secrets.CLOUDWATCH_LOG_GROUP }}
        run: pytest